services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qsomazzi\Particle\:
    resource: '../src/'

  Qsomazzi\Particle\Menu\MenuBuilder:
    arguments:
      $homepage: '%qsomazzi_particle.homepage%'
    tags:
      - { name: knp_menu.menu_builder, method: createParticleMenu, alias: particle }
