services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $qsomazziParticlePrefix: '%qsomazzi_particle.prefix%'
      $qsomazziParticleHomepage: '%qsomazzi_particle.homepage%'
      $qsomazziParticleTemplates: '%qsomazzi_particle.templates%'

  Qsomazzi\Particle\:
    resource: '../src/'

  Qsomazzi\Particle\Menu\MenuBuilder:
    tags:
      - { name: knp_menu.menu_builder, method: createParticleMenu, alias: particle }
